config/routes.rb
Rails.application.routes.draw do
  get 'users/company_data'

  get 'users_controller/company_data'

  resources :companies
  resources :cars
  get 'cars/new'
  get 'static_pages/home'
  get 'sessions/new'
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/company', to: 'users#company_data'
  resources :users
end

app/models/car.rb
class Car < ApplicationRecord
	
	belongs_to :company

	validates :make, presence: true
	validates :model, presence: true
	VALID_IMAGE_REGEX = /https?:\/\/([a-z]*.)+(jpg|png|jpeg)/i
	validates :image, presence: true
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all.order("created_at DESC").paginate(:page => params[:page], 
                                                      :per_page => 9)
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    if logged_in?
      if current_user.company.name != '<brak>'
        @car = Car.new
      else
        flash[:danger] = 'Przed dodaniem samochodu trzeba uzupełnić dane firmy!'
        redirect_to '/company'
      end
    else
      redirect_to login_path
    end
  end

  # GET /cars/1/edit
  def edit
    if !logged_in?
      flash[:danger] = 'Najpierw trzeba się zalogować!'
      redirect_to cars_path
    else
      if @car.company != current_user.company
        flash[:danger] = 'Samochód nie należy do twojej firmy!'
        redirect_to cars_path
      end
    end
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)
    
    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Samochód został utworzony.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Dane samochodu zostały zaktualizowane.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    if !logged_in?
      flash[:danger] = 'Najpierw trzeba się zalogować!'
      redirect_to cars_path
    else
      if @car.company == current_user.company
        @car.destroy
        respond_to do |format|
          format.html { redirect_to cars_url, notice: 'Samochód został usunięty.' }
          format.json { head :no_content }
        end
      else
        flash[:danger] = 'Samochód nie należy do twojej firmy!'
        redirect_to cars_path
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:make, :model, :image, :company_id)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for(car) do |f| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :marka %>
    <%= f.text_field :make %>
  </div>

  <div class="field">
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>

  <div class="field">
    <%= f.label :link_do_zdjęcia %>
    <%= f.text_field :image %>
  </div>

  <%= f.hidden_field :company_id, value: current_user.company_id.to_s %>

  <div class="actions">
    <%= f.submit "Zatwierdź" %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Edytuj samochód</h1>
<% provide(:title, 'Edycja samochodu') %>

<%= render 'form', car: @car %>

<%= link_to 'Pokaż', @car %> |
<%= link_to 'Wróć', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>
<% provide(:title, 'Samochody') %>

<h1>Samochody</h1>

<ul class="cars-list">
  <% @cars.each do |car| %>
    <li class="car-element">
      <%= link_to image_tag(car.image, size: "256x192"), car %>
      <div>
        <%= link_to car.make + ' ' + car.model, car, class: "lead" %>
      </div>
      <%= link_to 'Edytuj', edit_car_path(car) %>
      <%= link_to 'Usuń', car, method: :delete, data: { confirm: 'Na pewno?' } %>
    </li>
  <% end %>
</ul>

<br>

<div id="footer">
  <%= link_to "Dodaj samochód", new_car_path, class: "btn btn-lg btn-default" %>
  <br>
  <%= will_paginate @cars %>
</div>

app/views/cars/new.html.erb
<h1>Nowy samochód</h1>
<% provide(:title, 'Dodawanie samochodu') %>

<%= render 'form', car: @car %>

<%= link_to 'Wróć', cars_path %>

app/views/cars/show.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyCVRckajyyjIb3MPhMRI3aE3jgcjjDBerI"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>

<p id="notice"><%= notice %></p>
<% provide(:title, @car.make + " " + @car.model) %>

<h2><%= @car.make %>
  <%= @car.model %></h2>

<p>
  <img src=<%= @car.image %> alt="car-image" width="640" height="480" />
</p>

<p>
  Do kupienia w <%= link_to @car.company.name, '/companies/' + @car.company.id.to_s %><br/>
  <strong>Adres:</strong>
  <%= @car.company.address %><br/>

  <div id="map" style='width: 600px; height: 500px; left: 10%;'></div>

	<script type="text/javascript">
		handler = Gmaps.build('Google');
		handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
		  markers = handler.addMarkers([
		    {
		      "lat": <%= @car.company.latitude %>,
		      "lng": <%= @car.company.longitude %>,
		      "infowindow": "<%= @car.company.name + " - " + @car.company.address %>"
		    }
		  ]);
		  handler.bounds.extendWith(markers);
		  handler.fitMapToBounds();
		});
	</script>
</p>

<%= link_to 'Edytuj', edit_car_path(@car) %> |
<%= link_to 'Wróć', cars_path %>