config/routes.rb
Rails.application.routes.draw do
  get 'users/company_data'

  get 'users_controller/company_data'

  resources :companies
  resources :cars
  get 'cars/new'
  get 'static_pages/home'
  get 'sessions/new'
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/company', to: 'users#company_data'
  resources :users
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Salon samochodowy</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Salon samochodowy", home_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li><%= link_to "Firma", '/company' %></li>  
            <% end %>
            <li><%= link_to "Przeglądaj samochody", cars_path %></li>
            <li><%= link_to "Strona główna",   home_path %></li>

            <% if logged_in? %>
			  <li><%= link_to 'Wyloguj się' + ' ' + current_user.email, logout_path, method: :delete %></li>
			<% else %>
			  <li><%= link_to 'Zaloguj się', login_path %></li>
			  <li><%= link_to "Zarejestruj się",   signup_path %></li>
			<% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>